---
title: "Section 1 Excercise"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### 1.3 Get Excercise

#### import data
```{r}
diamond <- read.csv('/Users/mosaic/Desktop/文件夹/笔记/网课笔记/R Prigramming A-Z/1. Intro/Mispriced-Diamonds.csv')
```

#### get package ggplot2
```{r}
#install.packages("ggplot2")
library("ggplot2")
```

#### scatter plot
```{r}
ggplot(data=diamond[diamond$carat<2.5,], #filter insignificant data points
       aes(x=carat, y=price, colour=clarity)) + #add colors
  geom_point(alpha=0.1) + #make the points transparent 
  geom_smooth() 
    #add a smoothing line in order to see what the trends look like
    #the smoothing line comes after our points which means it is another layer added onto our   graph
    #geom_smooth() function adds confidence bands on the smooth as well. We can remove these by adding se=FALSE inside the geom_smooth() function
```

### conclusion 
#### 1F has the best clarity and I1 has the worst clarity 
#### Line crossing means ？
